version: '3.1'
services:
  payments-api:
    image: mwrona/sample-payments-api:latest
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo:4.1.3
    restart: always
    hostname: mongo
    volumes:
      - ./.mongodb:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
